services:
  pdf-reader:
    # mem_limit: 2048m
    build: .
    # ports:
    #   - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    networks:
      - nginx_bridge

networks:
  nginx_bridge:
    external: true